name: Push Docker container 
on:
   workflow_run:
    workflows: ["Frontend Tests Coverage", "Backend Tests Coverage", "Code Quality"]
    types:
      - completed

jobs:
  Backend-Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
         registy: bobapp-front
         context: ./front
         file: ./Dockerfile
         push: true
         tags: latest
         labels: front-latest

