# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Tests Coverage

on:
  pull_request:
    branches: ['main']

jobs:
  Run-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Installing Deps
        run: npm ci

      - name: Running Tests and generating coverage
        run: npm run test:prod

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: Karma Tests Reports
          path: front/coverage
